export default stats = {
    minutesWithStats: {type: [Number]},
    ratings: {type: Object},
    shotsTotal: {type: Object},
    shotsOffTarget:{type: Object},
    shotsBlocked: {type: Object},
    clearances: {type: Object},
    interceptions: {type: Object},
    possession: {type: Object},
    touches: {type: Object},
    passesTotal: {type: Object},
    passesAccurate: {type: Object},
    passesKey: {type: Object},
    passSuccess: {type: Object},
    aerialsTotal: {type: Object},
    aerialsWon: {type: Object},
    aerialsSuccess: {type: Object},
    offensiveAerials: {type: Object},
    defensiveAerials: {type: Object},
    cornersTotal: {type: Object},
    cornersAccurate: {type: Object},
    throwInsTotal: {type: Object},
    throwInsAccurate: {type: Object},
    throwInAccuracy: {type: Object},
    offsidesCaught: {type: Object},
    foulsCommitted: {type: Object},
    tacklesTotal: {type: Object},
    tackleSuccessful: {type: Object},
    tackleUnsuccessful: {type: Object},
    tackleSuccess: {type: Object},
    dribbledPast: {type: Object},
    dribblesWon: {type: Object},
    dribblesAttempted: {type: Object},
    dribblesLost: {type: Object},
    dribbleSuccess: {type: Object},
    dispossessed: {type: Object},
    errors: {type: Object},
}